name: Feature Build

on:
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  configure:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install depenencies
        run: yarn install

      - name: Build for Production
        run: yarn build

  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Deploy build to AWS S3
        run: aws s3 sync ./build/ s3://${{ secrets.AWS_S3_BUCKET_TEST }} --delete
